#!/bin/zsh
#
# Autor: Kai Wilke <kiste@netzworkk.de> 13.05.2014
#
# Script: kwvcdburn, kreiert und brennt (S)VCD Filme
# Version: 0.0.9
#

trap 'setterm -inversescreen off ; setterm -reset ;
rm -rf $gv_WorkDir &>/dev/null' EXIT INT

gv_ScriptName=${0##*/}

#
# Verzeichniss in denen nach Funktionen gesucht wird
#
if [ -f /usr/local/share/kwtools/functions/sys/script_init ] ; then
	PREFIX=/usr/local
else
	PREFIX=/usr
fi
Script_init_Fpath="${PREFIX}/share/kwtools/functions/sys"
export TEXTDOMAINDIR="${PREFIX}/share/locale"
export TEXTDOMAIN="$gv_ScriptName"

if [ -z ${(M)${FPATH}##*${Script_init_Fpath}*} ] ; then
	FPATH=${Script_init_Fpath}:${FPATH}
fi

autoload -U script_init

# Scriptinitialisierung
script_init

# auf Programme pruefen
prog_check vcdimager
if [ -n "${NO_PROGS[1]}" ] ; then
	exit 0
fi

# Soll die alte Konfiguration uebernommen werden (ja/nein)?
if [ -f "${gv_HomePath}/.kwtools/vcdburnrc" -a ! -f "${gv_HomePath}/.kwtools/kwvcdburnrc" ] ; then
	CONVERT_TITLE=$(gettext 'Konfigurationsuebernahme')
	CONVERT_MSG=$(gettext 'Soll die Konfigurations Datei ${gv_HomePath}/.kwtools/vcdburnrc nach ${gv_HomePath}/.kwtools/kwvcdburnrc uebernommen werden (ja/nein)? Bei nein wird die alte Konfigurationsdatei nur geloescht.')
	yesno "$CONVERT_TITLE" "$CONVERT_MSG" "yes"
	if [ "$gv_Auswahl" != no ] ; then
		mv "${gv_HomePath}/.kwtools/vcdburnrc" "${gv_HomePath}/.kwtools/kwvcdburnrc" &>/dev/null
	else
		rm "${gv_HomePath}/.kwtools/vcdburnrc" &>/dev/null
	fi
fi

# Konfigurationen einlesen
read_file kwvcdburnrc

# Variablen
if [ -z "$FILM_DIR" ] ; then
	FILM_DIR="$HOME"
fi	
if [ -z "$VCD_TYPE" ] ; then
	VCD_TYPE="svcd"
fi

CREATE_NAME_MSG=$(gettext 'Vergeben Sie einen Namen fuer die Video-CD ohne .cue Endung, ansonsten heisst sie videocd.cue.')

# Funktion haupt_menue{{{
lv_Video_Cd=$(gettext 'Video-CD')
lv_Burn=$(gettext 'brennen')
MAIN_MENU=($gv_Configuration \"\" $lv_Video_Cd \"\" $lv_Burn \"\" $gv_Back \"\")
#
haupt_menue() {
	menubox "$1" "$gv_Mainmenu" "$gv_Menupoint" "$MAIN_MENU"
}
#}}}

##############################################################
#
# Hauptprogramm
#
##############################################################
#
hw_conf
cdrom
haupt_menue
while [ "$gv_Auswahl" ] ; do
	case $gv_Auswahl in
		HELP*)
    	    # Hilfe Messagebox
			script_help help
			haupt_menue
			;;
		$gv_Configuration)
			# Konfiguration der ~/.kwtools/kwvcdburnrc# {{{
			autoload -U kwvcdburn_conf kwvcdburn_config
			kwvcdburn_conf
			## }}}
			haupt_menue $gv_Configuration
			;;
		$lv_Video_Cd)
			# VCD Image erstellen{{{
			#
			# Entweder mehrere Filme zusammenpacken film1 film2 ...
			# oder einzeln. Groesse zusammenrechnen.
			PROG=vcdimager
			FORMAT="MPEG sequence"
			SUFFIX=".mpg .mpeg .MPG .MPEG"
			# Werte auch in $gv_LogFile$$ schreiben
			U_OPT=no
			file_choice "$FILM_DIR" multi
			#
			if [ "${WERT[1]}" ] ; then
				VIDEO_TITLE=($lv_Video_Cd)
				#
				# Programm vcdimager ausfuehren.
				#
				typeset -L V_Anz
				V_Anz=`wc -l <$gv_LogFile$$`
				#
				# Soll eine VCD Struktur fuer alle Dateien erstellt werden,
				# wenn es mehr als eine Datei gibt (ja/nein)?
				if [ "$V_Anz" -gt 1 ] ; then
					CREATE_MULTI_QUESTION_MSG=$(gettext 'Soll aus allen Dateien eine einheitliche Video-CD Struktur erzeugt werden (Ja/nein)?')
					yesno "$VIDEO_TITLE" "$CREATE_MULTI_QUESTION_MSG"
					if [ "$?" = 0 ] ; then
						# Dateinamen vergeben
						inputbox "$VIDEO_TITLE" "$CREATE_NAME_MSG"
						if [ -n "$gv_Auswahl" ] ; then
							FILE_NAME="$gv_Auswahl"
							CREATE_MULTI_MSG=$(gettext 'Erzeuge Video-CD ${FILE_NAME}.cue aus de(r/n) Dateie(n) ${FILE_NAME}.')
							# zusammenfuegen
							$PROG -t $VCD_TYPE -c ${FILE_NAME%.*}.cue -b ${FILE_NAME%.*}.bin $WERT | \
							progressbox "$VIDEO_TITLE" "$CREATE_MSG" || prog_failure
						else
							no_input_msg
						fi
					else
						# alle Dateien einzeln umwandeln.
						Anz=1
						CREATE_MSG=$(gettext 'Erzeuge Video-CD: ${file% }.')
						while read file ; do
							$PROG -t $VCD_TYPE -c ${file%.*}.cue -b ${file%.*}.bin --volume-count=$V_Anz --volume-number=$Anz ${file% } | \
								progressbox "$VIDEO_TITLE" "$CREATE_MSG" || prog_failure
							(( Anz++ ))
						done <$gv_LogFile$$
					fi
				else
					# einzelne Datei umwandeln
					$PROG -t $VCD_TYPE -c ${WERT%.*}.cue -b ${WERT%.*}.bin ${WERT% } | \
					progressbox "$VIDEO_TITLE" "$CREATE_MSG" || prog_failure
				fi
				rm -rf $gv_LogFile$$ &>/dev/null
			fi
			#}}}
			haupt_menue $lv_Video_Cd
			;;
		$lv_Burn)
			# Film brennen# {{{
			multi_conf
			cd_dvd_burn --vcd
			## }}}
			haupt_menue $lv_Burn
			;;
		$gv_Exit)	break
			;;
	esac
done	
#
# umounten des Mount-Verzeichnis
if [ "$MOUNT_PATH" ] ; then
	mount_check -u $MOUNT_PATH
fi
unset -- FILM_DIR gv_Auswahl MOUNT MOUNTDIR FORMAT VCD_TYPE CDROM VOLUME_SET VOLUME_COUNT V_Anz
exit 0
### Modeline {{{
### vim:ft=zsh:foldmethod=marker
### vim:set ts=4:                                                                               
### }}}
