'\" t
.\"     Title: KWBTRFS.CF
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 09/16/2016
.\"    Manual: Benutzer Anleitung
.\"    Source: Version 0.0.1
.\"  Language: English
.\"
.TH "KWBTRFS\&.CF" "5" "09/16/2016" "Version 0.0.1" "Benutzer Anleitung"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kwbtrfs.cf \- Konfigurationsdatei f\(:ur kwpwsafe\&.
.SH "BESCHREIBUNG"
.PP
Beim Start von
\fBkwbtrfs\fR
wird die Datei
\fI/etc/kwtools/kwbtrfs\&.cf\fR
eingelesen\&. Sie beinhaltet die Variable die von
\fBkwbtrfs\fR
benutzt werden kann, um die Daten auf dem Dateisystem zu komprimieren\&. Beginnt eine Zeile mit
\(lq#\(rq
oder ist leer wird dies als Kommentar interpretiert\&.
.SH "VARIABELN"
.PP
\fBCOMPRESS\fR
.RS 4
Beinhaltet den Kompressions Algorithmus der standardm\(:assig aufdas Dateisystem angewendet werden soll\&.
.RE
.SH "DATEI"
.PP
\fI/etc/kwtools/kwbtrfs\&.cf\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBkwbtrfs\fR\&. F\(:ur weitere Details siehe
\fBkwbtrfs\fR(1)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBbtrfs\fR(5),
\fBbtrfs\fR(8),
\fBkwbtrfs\fR(8)
.SH "AUTHOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.RS 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2016 Kai Wilke
.br
