.\"     Title: MAIN.CF
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/15/2013
.\"    Manual: Benutzer Anleitung
.\"    Source: Version 0.3.1
.\"
.TH "MAIN\&.CF" "5" "11/15/2013" "Version 0.3.1" "Benutzer Anleitung"

.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
main.cf \- Konfigurationsdatei f\(:ur alle kwtools Scripte.
.SH "BESCHREIBUNG"
.PP
Die Funktion
\(lq\fBscript_init\fR\(rq
liest die Variablen von der Datei
\fI/etc/kwtools/main\&.cf\fR
ein\&. Beginnt eine Zeile mit
\(lq#\(rq
oder ist leer wird dies als Kommentar interpretiert\&. Die ANSI\-Escape Sequenzen werden noch nicht von
\fBkwadmin\fR
ge\(:andert\&.
.SH "VARIABELN"
.PP
\fBKWTOOLS_PATH\fR
.RS 4
Hier kann man den Pfad zu den kwtools einstellen\&. Standard ist
\fI/usr/lib/kwtools\fR\&.
.RE
.PP
\fBLANGUAGE\fR
.RS 4
Hier stellt man die Sprache ein in der die Hilfeseiten und Nachrichten angezeigt werden soll\&. Zur Zeit geht nur
\fBde\fR=\fIdeutsch\fR
und
\fBen\fR=\fIenglisch\fR\&.
.sp
\fBNotiz:\fR
Wenn man die Sprache \(:uber
\fBkwadmin\fR
einstellt, muss man
\fBkwadmin\fR
neu starten damit
\fBkwadmin\fR
in der neuen Sprache angezeigt wird\&. Alle anderen Scripts \(:ubernehmen die Sprache gleich\&.
.RE
.PP
\fBTMP_PATH\fR
.RS 4
Hier stellt man das tempor\(:are Verzeichnis ein in dem die Scripte tempor\(:are Dateien anlegen d\(:urfen\&. Dieses Verzeichnis gilt f\(:ur alle Scripte\&. Sie k\(:onnen auch Variablen, wie $HOME benutzen (Beispiele:
\fI$HOME/tmp, /var/tmp\fR)\&.
.RE
.PP
\fBEDITOR\fR
.RS 4
Mit diesem Eintrag haben Sie die Auswahl wie Sie Dateien bearbeiten\&. Sie k\(:onnen hier einen
\(lqEditor\(rq
Ihrer Wahl einstellen\&. Zum Beispiel
\fB/usr/bin/vim\fR,
\fBemacs\fR,
\fBjoe\fR,
\fBdialog\fR, \&.\&.\&.\&. Der Wert
\fBdialog\fR
ist eine Ausnahme\&. Ist dieser Wert eingetragen oder leer wird die Dialogbox
\(lqeditbox\(rq
verwendet\&.
.RE
.PP
\fBPAGER\fR
.RS 4
Angabe eines Pagers, um Dateien seitenweise auf die Standardausgabe anzuzeigen (Beispiel:
\fBless\fR,
\fBmore\fR)\&.
.RE
.PP
\fBERROR\fR
.RS 4
Farbe der Fehlermeldungen\&. Dies sind ANSI Escape Sequenzen (\fBecho \-en \e033[1;31m]\fR
= fett rot)
.RE
.PP
\fBERROR_BG\fR
.RS 4
Farbe des Hintergrunds bei Fehlermeldungen\&. Dies sind ANSI Escape Sequenzen (\fBecho \-en \e033[0;47m]\fR
= grau)
.RE
.PP
\fBNORMAL\fR
.RS 4
Farbe f\(:ur normale Meldungen\&. Dies sind ANSI Escape Sequenzen (\fBecho \-en \e033[0;39m]\fR
= standard)
.RE
.PP
\fBINFO\fR
.RS 4
Farbe f\(:ur Info Meldungen\&. Dies sind ANSI Escape Sequenzen (\fBecho \-en \e033[1;33m]\fR
= gelb)
.RE
.PP
\fBGREEN\fR
.RS 4
Farbe f\(:ur andere Anzeigen\&. Dies sind ANSI Escape Sequenzen (\fBecho \-en \e033[1;32m]\fR
= gr\(:un)
.RE
.PP
\fBRED\fR
.RS 4
Farbe f\(:ur andere Anzeigen\&. Dies sind ANSI Escape Sequenzen (\fBecho \-en \e033[1;32m]\fR
= rot)
.RE
.PP
\fBBOLD\fR
.RS 4
Anzeige wird fett dargestellt\&. Dies sind ANSI Escape Sequenzen (\fBecho \-en \e033[1;32m]\fR
= fett)
.RE
.PP
.RS 4
\fBNotiz:\fR
Alle hier vorgestellten Farben kann man nur manuall \(:andern\&.
.RE
.SH "DATEI"
.PP
\fI/etc/kwtools/main\&.cf\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur alle kwtools Scripte F\(:ur weitere Details siehe auch
\fBkwadmin\fR(1)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBkwadmin\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
