#! /bin/sh
# prerm script for kwtools-multi-xmms2
#
# see: dh_installdeb(1)

set -e

case "$1" in
	remove|upgrade|deconfigure)
		DIR=/usr/share/kwtools/functions
		cd $DIR
		rm -rf kwxmms2 >/dev/null 2>&1
		rm -rf ${DIR%/*/*}/doc/kwtools-multi-xmms2 >/dev/null 2>&1
		exit 0
		;;
	failed-upgrade)
		;;
	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0


