#! /bin/sh
# prerm script for kwtools-sys-lvm
#
# see: dh_installdeb(1)

set -e

case "$1" in
	remove|upgrade|deconfigure)
		DIR=/usr/share/kwtools/functions
		rm -rf ${DIR}/kwcrypt* ${DIR}/kwecryptfs ${DIR}/kwlosetup \
			${DIR%/*/*}/doc/kwtools-sys-crypt >/dev/null 2>&1
		exit 0
		;;
	failed-upgrade)
		;;
	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0


