#! /bin/sh
# prerm script for kwtools-utils-pim
#
# see: dh_installdeb(1)

set -e

case "$1" in
	remove|upgrade|deconfigure)
		DIR=/usr/share/kwtools/functions
		cd $DIR
		for i in kwplaner kwtermin ; do
			rm -rf ${i}* >/dev/null 2>&1
		done
		rm -rf ${DIR%/*/*}/doc/kwtools-utils-pim >/dev/null 2>&1
		exit 0
		;;
	failed-upgrade)
		;;
	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0

