#! /bin/sh
# prerm script for kwtools-common
#
# see: dh_installdeb(1)

set -e

case "$1" in
	remove|upgrade|deconfigure)
		DIR=/usr/share/kwtools/functions
		if [ -d "$DIR" ] ; then
			cd $DIR
			rm -rf sys >/dev/null 2>&1
			rm -rf ${DIR%/*/*}/doc/kwtools-common >/dev/null 2>&1
		fi
		exit 0
		;;
	failed-upgrade)
        ;;
	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0


