'\" t
.\"     Title: KWBTRFS
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 09/16/2016
.\"    Manual: Benutzerhandbuch f\(:ur kwbtrfs
.\"    Source: Version 0.0.1
.\"  Language: English
.\"
.TH "KWBTRFS" "8" "09/16/2016" "Version 0.0.1" "Benutzerhandbuch f\(:ur kwbtrfs"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kwbtrfs \- ein Zshell Script zur Verwaltung des btrfs Dateisystems\&.
.SH "SYNOPSIS"
.HP \w'\fBkwbtrfs\fR\ 'u
\fBkwbtrfs\fR
.SH "BESCHREIBUNG"
.PP
Mit
\fBkwbtrfs\fR
kann man \fIbtrfs\fR Dateisysteme verwalten, erstellen, vergr\(:ossern, verkleinern, Laufwerke hinzuf\(:ugen, entfernen und tauschen, \fIext2/3/4\fR Dateisysteme nach \fIbtrfs\fR konvertieren, ver\- und unverschl\(:usselte \fIbtrfs RAID Arrays\fR erstellen, Subvolumes erstellen, l\(:oschen und vieles mehr\&.
.SH "OPTIONEN"
.PP
\fBkwbtrfs\fR
hat keine Kommandozeilen Optionen\&.
.SH "SIEHE AUCH"
.PP
\fBkwbtrfs.cf\fR(5),
\fBbtrfs\fR(5)
\fBbtrfs\fR(8)
.SH "AUTHOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.RS 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2016 Kai Wilke
.br
