'\" t
.\"     Title: KWCRYPTSETUP
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 09/12/2017
.\"    Manual: Handbuch f\(:ur kwcryptsetup
.\"    Source: Version 0.2.4
.\"  Language: English
.\"
.TH "KWCRYPTSETUP" "8" "09/12/2017" "Version 0.2.4" "Handbuch f\(:ur kwcryptsetup"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kwcryptsetup \- Zshell Script f\(:ur das Programm cryptsetup
.SH "SYNOPSIS"
.HP \w'\fBkwcryptsetup\fR\ 'u
\fBkwcryptsetup\fR
.SH "BESCHREIBUNG"
.PP
Mit
\fBkwcryptsetup\fR
k\(:onnen Sie verschl\(:usselte Laufwerke bzw\&. Container (Image\-Datei) erstellen\&. Daf\(:ur werden die Programme
\fBcryptsetup\fR,
\fBdmsetup\fR
und
\fBlosetup\fR
benutzt\&.
.SH "OPTIONEN"
.PP
\fBkwcryptsetup\fR
hat keine Kommandozeilen Optionen\&.
.SH "DATEI"
.PP
\fI~/\&.kwtools/kwcryptsetuprc\fR
.RS 4
Konfigurations Datei f\(:ur
\fBkwcryptsetup\fR\&. Siehe
\fBkwcryptsetuprc\fR(5)
f\(:ur weitere Details\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBcryptsetup\fR(8),
\fBdmsetup\fR(8),
\fBgpg\fR(1),
\fBkwcryptsetuprc\fR(5),
\fBopenssl\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.RS 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2002-2017 Kai Wilke
.br
