.\"     Title: KWGRUB
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/13/2013
.\"    Manual: Benutzerhandbuch f\(:ur kwgrub
.\"    Source: Version 0.2.12
.\"
.TH "KWGRUB" "8" "11/13/2013" "Version 0.2.12" "Benutzerhandbuch f\(:ur kwgrub"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwgrub \- ein Zshell Frontend Script f\(:ur grub
.SH "SYNTAX"
.HP 7
\fBkwgrub\fR
.SH "BESCHREIBUNG"
.PP
Mit
\fBkwgrub\fR
k\(:onnen Sie den Bootloader
\fBgrub\fR
verwalten\&. Dazu geh\(:ort die Konfiguration der Datei
\fI/boot/grub/menu\&.lst\fR
zu bearbeiten und
\fBgrub\fR
in den Master Boot Record (\fBMBR\fR), auf Diskette (\fBFloppy\fR) oder in den
\fBBootsektor\fR
einer Partition zu installieren\&. Dies gilt nur f\(:ur den Bootloader
\fBgrub\fR
noch nicht f\(:ur den Bootloader
\fBgrub2\fR\&.
.SH "OPTIONEN"
.PP
\fBkwgrub\fR hat keine Kommandozeilen Optionen.
.SH "DATEI"
.PP
\fI/boot/grub/menu\&.lst\fR
.RS 4
Konfiguration Datei f\(:ur
\fBkwgrub\fR\&. Siehe
\fBinfo grub\fR
f\(:ur weitere Details\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBgrub\fR(8),
\fBgrub-floppy\fR(8),
\fBgrub-install\fR(8),
\fBgrub-md5-crypt\fR(8),
\fBgrub-reboot\fR(8),
\fBgrub-terminfo\fR(8)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2013 Kai Wilke
.br
