'\" t
.\"     Title: KWDJBDNS
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/29/2016
.\"    Manual: Handbuch f\(:ur kwdjbdns
.\"    Source: Version 0.5.1
.\"  Language: English
.\"
.TH "KWDJBDNS" "1" "12/29/2016" "Version 0.5.1" "Handbuch f\(:ur kwdjbdns"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kwdjbdns \- ein Zshell Script f\(:ur die Administration von Dan Bernstein\*(Aqs DNS Servern\&.
.SH "SYNOPSIS"
.HP \w'\fBkwdjbdns\fR\ 'u
\fBkwdjbdns\fR
.SH "BESCHREIBUNG"
.PP
\fBkwdjbdns\fR
soll Ihnen helfen die Konfiguration der verschiedenen
\fIDNS\fR\-Server, von Prof\&.
\fBDan Bernstein\fR, zu bew\(:altigen und zu verwalten\&. Zuvor sollten Sie die Pakete
\fBdaemontools\fR,
\fBucspi\-tcp\fR
und
\fBdjbdns\fR
installieren\&. Entweder von
.sp
.if n \{\
.RS 4
.\}
.nf
http://cr\&.yp\&.to
.fi
.if n \{\
.RE
.\}
.sp
oder von einem Debian Server\&.
.PP
Mit den Patches von
.sp
.if n \{\
.RS 4
.\}
.nf
http://www\&.fefe\&.de/djbdns/
.fi
.if n \{\
.RE
.\}
.sp
besitzen die Tools von
\fBdjbdns\fR
auch
\fIIPv6\fR
Unterst\(:utzung\&. Bei Debian heist das Paket
\fBdbndns\fR\&.
.PP
Wenn nicht bei der Installation geschehen, legen Sie bitte die Accounts
Gdnslog
und die GServernamen mit identischen Gruppennamen, Homeverzeichnis=/nonexistent und Shell=/bin/false an\&.
.PP
\fBNotiz:\fR
Es gibt die
\fIDNS\fR\-Server
\fBaxfrdns\fR,
\fBdnscache\fR,
\fBpickdns\fR,
\fBrbldns\fR,
\fBtinydns\fR
und
\fBwalldns\fR\&.
.SH "OPTIONEN"
.PP
\fBkwdjbdns\fR
hat keine Kommandozeilen Optionen\&.
.SH "SIEHE AUCH"
.PP
\fBaxfrdns\fR(8),
\fBdnscache\fR(8),
\fBpickdns\fR(8),
\fBrbldns\fR(8),
\fBtinydns\fR(8),
\fBwalldns\fR(8)
.SH "AUTHOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.RS 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2002-2016 Kai Wilke
.br
